<h1><?php echo $this->bigtitle; ?></h1>
<?php
if (!$this->logged) {
?>
<form method="POST">
    <input type="text" name="username" />
    <input type="password" name="password" />
    <input type="submit" value="Login" name="login" />
</form>
<?php
} else {
?>
You are logged !
Welcome <?php echo $this->username; ?>
<form method="POST">
    <input type="submit" value="Logout" name="logout" />
</form>
<?php
}
?>