<h1><?php echo $this->bigtitle; ?></h1>
<div style="text-align:center;">
    <div style="width:300px;float:left;">
        <form method="GET">
            <fieldset>
                <legend>Method GET : </legend>
                <input type="text" name="param1" />
                <input type="text" name="param2" /><br />
                <input type="submit" value="Send" />
            </fieldset>
        </form>
    </div>
    <div style="width:300px;float:left;">
        <form method="POST">
            <fieldset>
                <legend>Method POST : </legend>
                <input type="text" name="param1" />
                <input type="text" name="param2" /><br />
                <input type="submit" value="Send" />
            </fieldset>
        </form>
    </div>
</div>

<div name="infos" style="margin-top:150px;">
    <hr />
    <table>
        <tr><td>Ip : </td><td><?php echo $this->ip; ?></td></tr>
        <tr><td>User Agent : </td><td><?php echo $this->userAgent; ?></td></tr>
        <tr><td>HTTP Method : </td><td><?php echo $this->method; ?></td></tr>
    </table>

    <table>
    <?php
    foreach ($this->params as $key => $value) {
        echo '<tr><td>' . $key . '</td><td>= ' . $value . '</td></tr>';
    }
    ?>
    </table>
</div>
